version: '3.3'

services:
  app:
    image: kry0z1/hello:latest
    container_name: hello
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app-network

  nginx:
    image: kry0z1/nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
