name: Deploy

on:
  push:
    paths:
      - 'hello/**'

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository_owner }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect changed services
        id: changed
        run: |
          CHANGED_SERVICES=$(git diff --name-only HEAD^ HEAD | awk -F/ '{print $1}' | sort | uniq)
          echo "services=$CHANGED_SERVICES" >> $GITHUB_OUTPUT
          echo "Changed services: $CHANGED_SERVICES"

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push changed services
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)

          for SERVICE in ${{ steps.changed.outputs.services }}; do
            if [ -f "$SERVICE/Dockerfile" ]; then
              TAG="$TIMESTAMP-$SHORT_SHA"
              echo "Building $SERVICE with tag $TAG"
              
              docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/$SERVICE:$TAG ./$SERVICE
              docker push ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/$SERVICE:$TAG
              
              echo "$SERVICE:$TAG" >> updated_services.txt
            fi
          done

      - name: Deploy to server
        if: ${{ steps.changed.outputs.services != '' }}
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          script: |
            cd /path/to/your/docker-compose/folder
            while read -r line; do
              SERVICE=$(echo $line | cut -d':' -f1)
              TAG=$(echo $line | cut -d':' -f2)
              docker-compose pull $SERVICE
              docker-compose up -d $SERVICE
              echo "Redeployed $SERVICE with $TAG"
            done < updated_services.txt
