name: Deploy

on:
  push:
    paths:
      - 'services/**'
      - 'docker-compose.yaml'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      full_restart: ${{ steps.check_changes.outputs.full_restart }}
      changed_services: ${{ steps.get_changed_services.outputs.changed_services }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Determine restart type
      id: check_changes
      run: |
        if git diff --quiet HEAD^ HEAD -- docker-compose.yml; then
          echo "full_restart=false" >> $GITHUB_OUTPUT
        else
          echo "full_restart=true" >> $GITHUB_OUTPUT
        fi

    - name: Identify changed services
      id: get_changed_services
      if: ${{ steps.check_changes.outputs.full_restart == 'false' }}
      run: |
        changed_services=""
        for dir in services/*/; do
          if git diff --quiet HEAD^ HEAD -- $dir || [ -z "$(ls -A $dir)" ]; then
            continue
          fi
          if [ -f "$dir/Dockerfile" ]; then
            changed_services+="$(basename $dir) "
          fi
        done
        echo "changed_services=${changed_services% }" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push changed services
      if: ${{ steps.check_changes.outputs.full_restart == 'false' }}
      run: |
        for service in ${{ steps.get_changed_services.outputs.changed_services }}; do
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$service:$GITHUB_SHA ./services/$service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$service:$GITHUB_SHA
        done

    - name: Build and push all services
      if: ${{ steps.check_changes.outputs.full_restart == 'true' }}
      run: |
        for dir in services/*/; do
          service=$(basename $dir)
          if [ -f "$dir/Dockerfile" ]; then
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$service:$GITHUB_SHA $dir
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/$service:$GITHUB_SHA
          fi
        done

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
    - name: SSH Deploy
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /server
          
          if [ "${{ needs.build_and_push.outputs.full_restart }}" = "true" ]; then
            # Full restart flow
            docker-compose down
            docker-compose pull
            docker-compose up -d
          else
            # Partial service update
            for service in ${{ needs.build_and_push.outputs.changed_services }}; do
              docker-compose pull $service
              docker-compose up -d --no-deps $service
            done
          fi
